### ISSUE TITLE
SEND AUTOMATED DM TO NEW FOLLOWERS

### ISSUE THREAD

**Issue by Oyetomi** [mediabots/InstagramBot-GUI-Python#1]
First of all Lovely bot and UI. I just started using it
Would be appreciated if you can implement this..
SEND AUTOMATED DM TO NEW FOLLOWERS
workflow--->
Download current followers into a list "username_followers.txt"
Scrape followers every X minutes, into the list "username_newfollowers.txt",
Subtract username_followers.txt - username_newfollowers.txt
if theres a new follower is detected send them a DM

**Comment by mediabots** [comment]
Thank you
I will add these kind of many features.
But only after when basic required features, such as: like,comment,posts are implemented successfully.
As you can see ,those features are listed in my UI , but not activated yet.

If any contributor want to add these Miscalinious features , they are welcome to do so

And whenever this feature is ready I will let you know, by replying on this issue.

Regards
