### ISSUE TITLE
Failed to execute script pyi_rth_qt4plugins

### ISSUE THREAD

**Issue by J4ker** [mediabots/InstagramBot-GUI-Python#10]
![mstsc_D9TStZtJ3U](https://user-images.githubusercontent.com/56275036/71299418-2b40b300-23b3-11ea-86b3-74ec3aa68fa0.png)

Tried launching both x64 and x32bit but no solution.
This is the error I am getting in the latest update 1.0.4

I noticed that the x32bit 1.0.4 version date modified -  4/12/19  is working fine ..... BUT
the latest one is not launching.

**Comment by mediabots** [comment]
Ok
You said 32biit of "4/12/19 is working fine", please state its hashcode if you can. 

When I first released ver 1.0.4 on December, I tried the Bot on Windows Server 2016, and there both version were working fine.
Then some users reported about that script error,etc for Windows 10.

So I installed Windows Server 2019 on my server, and I got the same error.
And I fixed the error successfully, Unfortunately, that fixed also named ver 1.0.4

At that time, I tested them on Windows Server 2019, both version were working then. 
Though now, only 64 bit version is running fine. 
And 32bit version was not launching unless I disabled Windows defender real time protection from Windows Setting!

Still now, on my machine Windows 8.1 , both 32 & 64 bit version are running fine.
 
I am assuming you are using Windows 10, correct?
please confirm

Looks like, I have to install a Virtual box to test the Bot on Windows 10

**Comment by mediabots** [comment]
**Please check latest version**
Re Download 32 bit or 64 bit
File sizes are 16.4MB & 19.2MB respectively

Hope this would fix the problem
Please don't forget to confirm, whether problem fixed or not

Thank you

**Comment by J4ker** [comment]
I use the Windows Server 2019 - Windows 10
Yeah when the first update of 1.0.4 on 4-12-2019 was pushed, the x64bit didn't work and gave the same error, but x32bit ran fine, and then when the latest update was pushed Both x64 & x32 bit gave the error.

And as of now, you are right, the 32bit is getting deleted by Windows Defender, and **64 bit is working fine without any problem.**

Thank You

**Comment by mediabots** [comment]
Thanks for the confirmation :)
