### ISSUE TITLE
Following Error

### ISSUE THREAD

**Issue by anonymoussssboy** [mediabots/InstagramBot-GUI-Python#13]
Hello, its great app  with many features but I have a problem with "Follow Instagram Users" feature. After following a few people, it is no longer able to do so. I tested this feature on several accounts, but it all happened.

> Error:
> [Err] https://www.instagram.com/mariasharapova/?__a=1 Page not responding properly! 
> Status Code: 429
> User does not exist
> continued
> 

None of the accounts have been blocked and can be follow users manually, But your bot can't.
Please explain why and tell me what to do.
Thank yo in advance.

**Comment by marakisir** [comment]
Hi! I had the same issue but the solution for me was:
1)After each username in follow.txt must have comma ( , ) without parenthesis
2)The follow.txt file must saved as ANSI.

**Comment by mediabots** [comment]
> 
> 
> Hi! I had the same issue but the solution for me was:
> 1)After each username in follow.txt must have comma ( , ) without parenthesis
> 2)The follow.txt file must saved as ANSI.

Does this really works?
I meant, after changing this thing, BOT can start following without any error?

I was busy in these days, so did not get into deeper of this issue!

**Comment by marakisir** [comment]
Yes it worked or me!

Στις Σάβ, 25 Ιαν 2020, 16:44 ο χρήστης MediaBOTS <notifications@github.com>
έγραψε:
