### ISSUE TITLE
Data Type Mistake?

### ISSUE THREAD

**Issue by zeroxyn** [mediabots/InstagramBot-GUI-Python#3]
Hi there, when trying to search for suitable followers it says '>>> could not convert string to float: '1,00'', therefore the search function doesnt work. Thx for any help!

**Comment by zeroxyn** [comment]
Ahh, I think it has to do with language settings of my OS as I am German and we use commas instead of dots for decimals. Just wanted to point this out in case you want to remove this bug ;) thank you for all your effort, you are great!!

**Comment by mediabots** [comment]
You are correct
Thanks for figuring out the issue.

Also in latest version(ver - 1.0,3) of the App, issue is fixed

Regards
