### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by zeroxyn** [mediabots/InstagramBot-GUI-Python#4]
Hi there, maybe someone can help me out..

I am getting an exception error when trying to find suitable users.

![qkW57NW](https://user-images.githubusercontent.com/57108903/67848653-60442e00-fb05-11e9-8b02-3aece12561b4.png)

**Comment by zeroxyn** [comment]
Sorry, wrong image. This is what I meant

![BrsMhzS](https://user-images.githubusercontent.com/57108903/67848804-abf6d780-fb05-11e9-845e-fa056979630a.png)

**Comment by zeroxyn** [comment]
Seems it has something to do with python requests? Do I have to import requests in cmd manually?

**Comment by mediabots** [comment]
No, it has nothing to do with the requests module.

Could share more data?
I meant, during which task, this problem occurred,etc?

Also, if you don't mind , could you share the LOG text file of that day. [Please, don't forget to remove vital details, such as your instagram username,id,etc ]

Though, I have looked into this, and made slight changed in the code of the function: get_user_id_by_username()

But,I want to be sure about, exactly what causing this Exception!

Thank you

**Comment by zeroxyn** [comment]
Hi, I currently do not have access to my PC but as soon as I will, I can send you the LOG files and some explanation of what I have done! Thank you a lot for looking into this :)

**Comment by zeroxyn** [comment]
After installing Python 3.5.0 and using your new version (1.0.3) it is working now :)

**Comment by mediabots** [comment]
Thanks "zeroxyn" for confirming :)

**Comment by mediabots** [comment]
Ok
Thanks for your confirmation


>Пятница,  8 ноября 2019, 16:13 +05:00 от zeroxyn <notifications@github.com>:
>
>After installing Python 3.5.0 and using your new version (1.0.3) it is working now :)
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

-- 
Media Bots
