### ISSUE TITLE
[Error] IG Login Challenge Failed!!

### ISSUE THREAD

**Issue by alx-xlx** [mediabots/InstagramBot-GUI-Python#6]
I am always getting this error, and I am not able to login

Please Help

**Comment by mediabots** [comment]
Make sure your account is functional/working.
To check that, login from a Web browser.

If your login is working in the Browser.
Then Click on LOGS button of the App(from top-left side), it will open a .text file.
Write down the text of it.

**Comment by alx-xlx** [comment]
I used the InstagramBot in another computer and it login successfully

Thanks for the Help

**Comment by mediabots** [comment]
Ok, it may be an IP issue.
Thanks for the update :)
