### ISSUE TITLE
[Feature Request] Stop specific Running Tasks

### ISSUE THREAD

**Issue by alx-xlx** [mediabots/InstagramBot-GUI-Python#7]
In v1.0.3 there are no provisions to stop a running task, to stop a task we have to completely close the program.
It would be great if there are provisions to stop specific running tasks.

**Comment by mediabots** [comment]
When that feature is ready,will let you know here

**Comment by mediabots** [comment]
Stop a Specific Task option introduced in "InstagramBOT" version 1.0.4
So, Please use the latest version of the BOT to have that feature

Thanks
