### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by 1appwebmail** [mediabots/InstagramBot-GUI-Python#8]
By default, it is taking local IP address even after adding the proxy, have checked the cookie txt, it does not show proxy and IG sends a mail with my local IP address of login

**Comment by mediabots** [comment]
Ope App Folder
go to 
user >> [IG_username]
Folder

then under that Folder,you should found cookie.txt and cookie(1.0.3).txt files.
Delete both of them.

Try now, see if it helps

**Comment by 1appwebmail** [comment]
The problem persist, still getting logged in with my LOCAL IP address

**Comment by mediabots** [comment]
Sorry for the delay
Please use newest BOT version (1.0.4)
Proxy BUG fixed there
