### ISSUE TITLE
Request - "Repost from a Hashtag"

### ISSUE THREAD

**Issue by J4ker** [mediabots/InstagramBot-GUI-Python#9]
In the Section "Repost from a Hashtag" >> Basic Options Menu

Please add a system where we can @mention the user who posted the #hashtag

Thank You

**Comment by mediabots** [comment]
You meant to mention the original poster IG username? correct?
That could be generated & mentioned automatically.
Will add a tick mark option: "include original poster username" for that on next release

**Comment by J4ker** [comment]
Yes, thats what correct.
a tick mark option would be great, but using a variable would be much more meaningfull & customizable.
For example we could use %USERNAME% in the headers section to automatically mention the original user.
in the headers e.g - Credit : %USERNAME%

.

**Comment by mediabots** [comment]
ok will see
Whenever update is available, will let you know here

Thanks
